refactor ♻️ curr register count class validator
42Statistics/42Stat-Backend pull request #197
Opened 2023-06-28 10:25 UTC by niamu01

- close #195
- close #196

2023-06-28 11:43 UTC, jpham005 requested changes

2023-06-28 11:43 UTC, jpham005 commented on app/src/api/project/models/project.model.ts
> +import { MinLength } from 'class-validator';
이건 왜 생긴건가요?

2023-06-28 11:43 UTC, jpham005 commented on app/src/api/cursusUser/cursusUser.resolver.ts
> +    return await this.cursusUserService.findUserPreviewByLogin(name, limit);
ByLogin 인데 name 으로 찾는...
다른 쿼리라 다른 ArgsType 을 사용하는게 맞지 않나 하는 생각도 드네요.

2023-06-28 11:43 UTC, jpham005 commented on app/src/api/projectsUser/projectsUser.service.ts
> +      .match({ createdAt: { $gte: new StatDate().moveMonth(-4) } })
이거 위쪽 줄이랑 합쳐도 될거같네요

2023-06-30 02:44 UTC, niamu01 commented on app/src/api/project/models/project.model.ts
> +import { MinLength } from 'class-validator';
project find랑 user find의 ArgsType을 따로 만들었을때 적었다가 남은것같네요... 
합쳤던걸 분리하면서 다시 생길예정입니다.

2023-06-30 05:38 UTC, jpham005 requested changes

2023-06-30 05:38 UTC, jpham005 commented on app/src/api/cursusUser/models/cursusUser.model.ts
이거 dtos 폴더 만들어서 거기다 넣어주세용

2023-06-30 05:38 UTC, jpham005 commented on app/src/api/project/project.resolver.ts
> +    @Args() { name }: projectSearchInput,
얘도 limit 들어가는게 나을 듯...

2023-06-30 05:41 UTC, niamu01 commented on app/src/api/project/project.resolver.ts
> +    @Args() { name }: projectSearchInput,
으악 👌

2023-06-30 09:37 UTC, jpham005 requested changes

2023-06-30 09:37 UTC, jpham005 commented on app/src/api/cursusUser/dtos/cursusUser.dto.ts
min max 둘 다 넣어주세용

2023-06-30 09:49 UTC, jpham005 approved these changes

2023-06-30 09:50 UTC, merged