feat ✨ login & setting page
42Statistics/42Stat-Backend pull request #218
Opened 2023-07-08 11:12 UTC by niamu01

- close #210

2023-07-12 23:41 UTC, jpham005 requested changes
일단 로직 내에서 고쳐야 하는 부분들 먼저 진행하고,
구글 로그인 호출하는 부분은 따로 분리해봅시다.

2023-07-12 23:41 UTC, jpham005 commented on app/src/login/login.service.ts
> +  }
이거 보니까 그냥 google 처럼 계정 연동해주는 서비스들은 분리하는게 낫겠네요

2023-07-13 05:25 UTC, niamu01 commented on app/src/login/login.module.ts
> +  exports: [LoginService],
setting page에서 사용중이라 유지했습니다

2023-07-13 05:37 UTC, niamu01 commented on app/src/login/models/login.model.ts
> +        return NoAssociated;
NotLinked 로 변경했습니다

2023-07-13 05:41 UTC, niamu01 commented on app/src/login/db/account.database.schema.ts
> +  createdAt: Date;
signedUpAt 으로 변경했습니다

2023-07-14 13:21 UTC, niamu01 commented on app/src/page/setting/setting.service.ts
> +    };
로그인 제외하기로 했습니다 👍

2023-07-15 09:45 UTC, jpham005 requested changes

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +  async getGoogleUser(input: GoogleLoginInput): Promise<GoogleUser> {
이 부분은 reference 확인이 아직 필요해보이네요
verifyIdToken 함수 관련해서 자세히 보면 좋을 것 같습니다

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +  }
마찬가지로 interface 를 이용한 구현으로 변경 부탁드립니다

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +        { userId, accessToken: newAccessToken, refreshToken },
refresh token 으로 찾도록 합시다

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +      };
update 의 new option 을 활용하는걸로 바꿉시다

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +    try {
try catch block 확인 한번 해주세요

2023-07-15 09:45 UTC, jpham005 commented on app/src/auth/statAuthGuard.ts
> +  }
user id 와 access token (split 이후) 를 모두 저장하도록 합시다

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +    const token = accessToken.split(' ')[1];
수정하면 여긴 필요없어질겁니다

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +    }
나중에 정리해주세요

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +    });
deleteMany 에 filter 를 바로 넣어도 괜찮을 것 같네요

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/login.service.ts
> +  @Cron('0 0 * * *')
시간을 새벽 5시 처럼 사람들 정말 없을 시간에 하는게 나아보입니다.

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/models/login.model.ts
> +export class Success {
클래스 이름 앞에 접두사 붙여주세요

2023-07-15 09:45 UTC, jpham005 commented on app/src/login/models/login.model.ts
> +}
여기도 interface 로 교체합시다

2023-07-15 09:45 UTC, jpham005 commented on app/src/page/setting/models/setting.model.ts
UserAccount 를 활용하는 방향으로 바꿉시다

2023-07-15 09:45 UTC, jpham005 commented on app/src/config/config.register.ts
> +  }
get 붙이거나 수정이 필요할 것 같습니다

2023-07-15 14:04 UTC, niamu01 commented on app/src/login/login.service.ts
> +        audience: input.clientId,
clientId를 넣는건 맞는데 
https://developers.google.com/identity/sign-in/web/backend-auth

예시를 보니까 idToken자리에 잘못 넣고 있었던것같네요
https://github.com/googleapis/google-auth-library-nodejs/blob/main/samples/verifyIdToken.js

2023-07-15 14:04 UTC, niamu01 commented on app/src/login/login.service.ts
> +        audience: input.clientId,
아 input의 clientId가아니라 google의 clientId를 넣는게 맞습니다

2023-07-18 01:50 UTC, jpham005 requested changes
lean 에 대해서 고민을 해봐야겠군요

2023-07-18 01:50 UTC, jpham005 commented on app/src/auth/statAuthGuard.ts
> +    return true;
```ts
const authString = context.req.header('Authorization');

const verifyContext = await this.verifyToken(authString);
Object.assign(context, verifyContext);

return true;
```

2023-07-18 01:50 UTC, jpham005 commented on app/src/auth/statAuthGuard.ts
> +      throw new UnauthorizedException('Invalid token format');
여기도 메세지 필요없겠네요

2023-07-18 01:50 UTC, jpham005 commented on app/src/auth/statAuthGuard.ts
> +    accessToken: string | undefined,
authString

2023-07-18 01:50 UTC, jpham005 commented on app/src/config/configuration/client.config.ts
ftClient 가 더 맞겠네요

2023-07-18 01:50 UTC, jpham005 commented on app/src/config/configuration/google.config.ts
이건 googleClient 가 되겠고요

2023-07-18 01:50 UTC, jpham005 commented on app/src/lambda/lambda.register.ts
이건 커밋에서 빼주세용

2023-07-18 01:50 UTC, jpham005 commented on app/src/login/models/login.model.ts
> +  @Field()
{ nullable: true }

2023-07-18 01:50 UTC, jpham005 commented on app/src/login/login.service.ts
> +  }
account module 만들 수 있을 것 같은데요?

2023-07-18 01:50 UTC, jpham005 commented on app/src/login/login.service.ts
> +    });
googleId 에서 필드이름이 변경되어야겠죠?

2023-07-19 14:11 UTC, jpham005 requested changes
주석은 형식 맞추거나 삭제 부탁드리고...
lean 어떤 방식으로 추상화할지는 여전히 문제네요.

2023-07-19 14:11 UTC, jpham005 commented on app/src/login/login.service.ts
> +      'linkedAccount.linkedPlatform': 'google',
linkedAccounts.platform으로 하죠

2023-07-19 14:11 UTC, jpham005 commented on app/src/login/login.service.ts
> +      { new: true, lean: true },
.lean() 사용하는걸로 컨벤션 업데이트 부탁드립니다

2023-07-20 11:05 UTC, niamu01 commented on app/src/login/login.service.ts
> +  async linkGoogle(userId: number, account: LinkedAccount): Promise<account> {
upsert기능을 insert로 변경하니 코드가 짧아져 javascript로 변경하지는 않았습니다

2023-07-20 11:31 UTC, niamu01 commented on app/src/config/configuration/ftClient.config.ts
> +export interface FtClientConfig {
문서 예제에서는 interface로 사용하고 있었는데 type으로 했을 때 더 좋은 점이 있나요?
일단 확장 가능성은 없습니다

2023-07-21 07:16 UTC, jpham005 approved these changes
고생 많으셨습니다.
이후 access token 과 refresh token 의 전달 방법과 저장소를 분리하는 것도 고려해야 하겠네요.

2023-07-21 07:16 UTC, merged