feat: :sparkles: winCountPerCoalition 추가
42Statistics/42Stat-Backend pull request #323
Opened 2023-09-01 10:36 UTC by niamu01

- close #321

2023-09-02 06:41 UTC, jpham005 requested changes

2023-09-02 06:41 UTC, jpham005 commented on app/src/page/home/coalition/home.coalition.service.ts
> +  @CacheOnReturn()
Cache 해야하나요?

2023-09-02 06:41 UTC, jpham005 commented on app/src/api/score/score.service.ts
> +      .project({ _id: 0, coalition: { $first: '$coalitions' }, value: 1 });
이거 줄바꿈 하는 기준을 세울 필요가 있겠네요.
그전까진 차라리 전부 줄바꿈하는게 나을 것 같기도 하구요.
위엔 단순 sort 하는 것도 두줄에 걸쳐 작성되어있는데,
이렇게 deps 가 중첩되는 경우는 또 한줄로 되어있어 보기 좀 그렇긴 하네요.

2023-09-02 12:14 UTC, niamu01 commented on app/src/api/score/score.service.ts
> +      .project({ _id: 0, coalition: { $first: '$coalitions' }, value: 1 });
aggregate 에서의 줄바꿈의 기준을
중괄호 내부에서 , 로 2개 이상의 필드가 생길 경우로 하는건 어떨까요..?
```ts
.sort({
  at: 1,
  value: -1,
})
```
```ts
.project({
  _id: 0,
  coalition: { $first: '$coalitions' },
  value: 1,
});
```
이런 식으로요

또한 이렇게 내부에 줄바꿈 해야하는 경우엔 앞 단계들도 다 나눠지고...
```ts
records: {
  $push: {
    at: {
      $dateFromString: {
        dateString: '$_id.at',
        timezone: process.env.TZ,
      },
    },
    value: '$value',
  },
}
```

만약 모든 필드가 1개라 줄바꿈을 할 일이 없으면
```ts
records: { $push: { at: {$dateFromString: {dateString: '$_id.at'} } } }
```
이렇게 되는데, 이런 경우엔 3 deps 까지만 한 줄로 두고 줄바꿈 하는건 어떨까 싶네용
```ts
records: {
  $push: {
    at: { $dateFromString: { dateString: '$_id.at' } },
  },
},
```

2023-09-02 13:20 UTC, niamu01 commented on app/src/page/home/coalition/home.coalition.service.ts
> +  @CacheOnReturn()
캐시하는 쿼리들의 기준이 오래걸리는 쿼리라고 생각했는데 
tigCountPerCoalition 은 오래 걸리지 않지만 캐시하고 있어서 winCount 도 같은 계열이라 생각해 똑같이 만들었습니다

2023-09-02 21:30 UTC, jpham005 commented on app/src/page/home/coalition/home.coalition.service.ts
> +  @CacheOnReturn()
home 의 경우에는 모든 사용자가 같은 api 를 호출하기 때문에 되도록 cache 하는 것 입니다.

tigCountPerCoalition 은 오래 걸리지 않기 때문에 요청 시 cache 하고,
winCountPerCoalition 은 오래 걸리기 때문에 lambda service 에서 cache 해놓은 것으로 보입니다. (그렇지 않다면 lambda service 에서 cache 할 필요가 없습니다.)

lambda service 에서 cache 한 것을 반환하는 endpoint 인데,
cache 가 존재한 결과를 다시 cache 하는 것이 큰 의미가 없습니다. 오히려 데이터 갱신의 반영 시점만 늦어지겠죠.
따라서 lambda service 에서 cache 해놓은 endpoint 들은 CacheOnReturn 으로 중복 cache 를 생성할 필요가 없습니다.

2023-09-02 21:31 UTC, jpham005 reviewed
cache 관련 부분 확인해보세요

2023-09-03 08:26 UTC, niamu01 commented on app/src/page/home/coalition/home.coalition.service.ts
> +  @CacheOnReturn()
아! 코드 작성하면서 약간 의아한 부분이 있었는데 이제 이해가 되네요.
lambda 에서 cache 하는 부분을 제외하고 요청 시 cache 하는 부분만 남겨두는걸로 변경했습니다.

2023-09-03 11:48 UTC, jpham005 approved these changes

2023-09-03 12:29 UTC, merged