fix: :bug: 코알리숑이 없는 유저의 코알리숑 순위에서 throw 를 0 반환으로 수정
42Statistics/42Stat-Backend pull request #336
Opened 2023-09-26 07:18 UTC by niamu01

고민하다가 조금 돌아왔는데 생각했던 것에 대해 이슈에 적어뒀습니다.
다른 좋은 방법이 생각났다면 알려주세요 💭 

- close #333

2023-09-26 09:22 UTC, jpham005 commented
1. null 이 아니라 undefined 반환하는 이유가 뭔가요?
2. 이슈 읽어봤는데, 현재 방식의 어떤 부분이 문제가 되는 건가요?

2023-09-26 11:08 UTC, jpham005 commented
@niamu01

2023-09-26 14:20 UTC, niamu01 commented
@jpham005 
1. 타입이 number | null 이 아닌 ?: number 로 되어있어서 undefined 만 반환이 가능한 상태입니다.
2. 아직 입과하지 않은 유저는 코알리숑이 없어 유저 정보 페이지에서 scoreInfo 를 불러올 때 NotFound 가 throw 되고 있습니다. throw 보다는 코알리숑이 없음을 반환해주는게 좋다고 생각했습니다.

2023-09-26 14:39 UTC, jpham005 commented
이슈의 1번과 2번 방식의 차이가 궁금한거긴 해요

2023-09-27 05:34 UTC, niamu01 commented
아하
1번은 지금처럼 랭킹에 안넣고 2번은 scoreRanking 를 구할 때 aggregate 를 수정해 랭킹에 넣는다는 점이 다르고,
원하는 반환값으로 주려면 1번이 더 맞다는 결론이 이슈의 내용이었습니다.
진짜로 notFound일 수도 있는데 throw 하던 부분을 고정값 반환으로 한다는 점에서 조금 신경쓰여서 아예 다른 방식으로 구분할 수 있지 않았을까 를 고민하고 있었습니다.

2023-09-27 14:47 UTC, jpham005 requested changes
제가 이해한 바로는, 문제는 이렇습니다.

1. 유저가 존재하는데 코알리숑이 없음
2. 유저가 존재하지 않음

지금처럼 처리하면 이것이 구분이 되지 않아서 문제라는 것으로 이해했고,
이걸 해결하려면 scoreRanking aggregation 을 바꾸는게 맞을 것 같네요.

coaltions_users 없는 경우를 그냥 빼버리고 있었는데,
어차피 관련 타입도 전부 nullable 하게 해놔서 그 빼는 작업만 없이 하면 될 것 같아요

2023-09-30 16:53 UTC, niamu01 commented
코알리숑 우승같은 항목은 획득한 유저의 id 가 null 로 되어있어 cond 를 한 번 사용하게 되었습니다 (score lookup 에서 처리해도 좋을 것 같네요)
랭킹을 함께 계산해서 `value:0 rankInCoaliton: 0 rankInTotal: 0`으로 반환되고 있습니다

2023-09-30 17:47 UTC, jpham005 approved these changes
애초에 여기저기서 coalitionsUserId 확인하는 부분을 없앨 수 있도록,
db 재설계하면 coalition 점수는 삭제할까 생각 중 입니다.

2023-10-03 23:29 UTC, merged