feat ✨ follow api 추가
42Statistics/42Stat-Backend pull request #412
Opened 2023-12-25 06:46 UTC by niamu01

- close #405 
- close #406

2023-12-29 13:31 UTC, niamu01 commented
뭔가 push 잘못해서 날라갔서용 잠시만요,,, @jpham005

2023-12-29 13:41 UTC, niamu01 commented
날라갈 뻔한 커밋 체리픽 완...! 👍

2023-12-30 05:07 UTC, jpham005 requested changes
caching 활용이 전혀 안되어 있어 이 부분은 근본적으로 고쳐야할 것으로 보이고,
db index 도 관리해야합니다. 지금은 아무것도 없더군요.

graphql model 도 잘 이해가 안되는 부분들이 있는데,
프론트와 같이 보면서 실제로 어떻게 사용하는지 살펴보고 고치던가 해야겠습니다.

2023-12-30 05:07 UTC, jpham005 commented on app/src/follow/follow.service.ts
> +  async checkFollowingStatus(
follower / following 목록을 가져올때 쓰이는 함수인데,
이 함수를 호출하기 전에 이미 following status 를 알고 있어야 정상으로 생각이 되긴 합니다

2023-12-30 05:07 UTC, jpham005 commented on app/src/follow/follow.service.ts
> +      if (userId !== user.id) {
이 분기도 이상하긴 하네요.

2023-12-30 05:07 UTC, jpham005 commented on app/src/follow/model/follow.model.ts
> +  isFollowing?: boolean;
nullable 해야하는 이유가 있나요?

2023-12-30 05:07 UTC, jpham005 commented on app/src/follow/follow.resolve.ts
> +  }
안쪽에서 exception 으로 처리하고 message 는 삭제하는게 낫겠네요

2023-12-30 05:07 UTC, jpham005 commented on app/src/follow/model/follow.model.ts
> +}
paginated 가 따로 있는 이유가 뭔가요?

2023-12-30 05:07 UTC, jpham005 commented on app/src/follow/model/follow.model.ts
> +});
message 삭제하면 전부 필요없겠네요

2023-12-30 08:22 UTC, niamu01 commented on app/src/follow/follow.service.ts
> +      }
앗.....! 안지워졌군요

2023-12-30 09:23 UTC, niamu01 commented on app/src/follow/follow.resolve.ts
https://docs.nestjs.com/graphql/subscriptions#publishing
여기에선 await 을 안 사용하고 있어서 await 없는채로 동작하는 것도 확인했는데, 실제로 pubSub.publish() 함수는 Promise<void> 반환하는 함수네용...
붙이는게 좋을까요?

2023-12-30 09:27 UTC, niamu01 commented on app/src/follow/follow.resolve.ts
> +  }
팔로우 리스트 화면으로 넘어가기 위한 카드에
미리보기로 (아마 3명정도...) 유저 이미지와 총 팔로우 수를 띄워주기로 해서 limit이 있는 list를 그대로 두었습니다.

2023-12-30 09:29 UTC, niamu01 commented on app/src/follow/follow.resolve.ts
> +  }
처음에 boolean 으로 했다가
```
내가 팔로우 안하는 유저 -> false
내가 팔로우 하는 유저 -> true
나 자신 -> null
```
이 되었습니다.

2023-12-30 13:28 UTC, jpham005 commented on app/src/follow/follow.resolve.ts
> +  }
pagination 함수에서 first 3 으로 하면 되지 않나요?

2023-12-30 13:39 UTC, jpham005 commented on app/src/follow/follow.resolve.ts
promise 는 기본적으로 await 하는게 좋은 건 맞고,
https://github.com/apollographql/graphql-subscriptions/blob/master/src/pubsub.ts
해당 링크에 pubsub 구현이 있는데 여기선 interface 때문에 async 함수로 만들긴 했지만 실제론 전부 동기로 작동해서 그닥 상관없어 보입니다.

하지만 내부에서도 async 동작이 생기면 await 해야하는 상황이 분명히 올거라고 봅니다.

2023-12-30 13:41 UTC, jpham005 commented on app/src/follow/follow.resolve.ts
> +  }
이건 논의가 좀 필요하겠지만,
애초에 targetUserId 가 아니라 targetLogin 을 받는 이유도 잘 모르겠습니다.

targetLogin 을 받는게 합당하더라도, 나 자신에 대해 특별히 처리해야 하는 이유도 모르겠구요.

2024-01-05 10:33 UTC, niamu01 commented on app/src/follow/follow.resolve.ts
> +  }
프론트에서 이 함수를 사용하는 모든 경우에 id를 가지고 있는지 몰라서 일단 login을 받도록 만들었었습니당
오늘 이야기 해보니 id로 요청 보내는 것도 가능하고, 나 자신 처리도 안해도 괜찮다구 하셔서 그럼 boolean반환으로 수정하겠다고 전달했습니다. 👍

2024-01-05 11:47 UTC, jpham005 commented on app/src/follow/follow.service.ts
> +};
eval log 는 id 도 nan 검사 가능할 것으로 생각됩니다.

2024-02-20 13:46 UTC, merged