Feat/cursus user
42Statistics/42Stat-Backend pull request #87
Opened 2023-05-11 05:05 UTC by niamu01

2023-05-11 06:36 UTC, jpham005 requested changes
역시 평균 서클 돌파기간 구하는 로직이 복잡하고 중복도 많은게 별로긴 하네요.
하지만 db 쿼리 시간을 보면 이렇게 만드는게 최적의 선택이라는게 딜레마입니다.
오래 걸리더라도 js 로직으로 통일시킬지 더 고민해야할 것 같습니다.

2023-05-11 06:36 UTC, jpham005 commented on app/src/quests_user/db/questsUser.database.schema.ts
> +}
요거 나중에 바꿔주세용

2023-05-11 06:36 UTC, jpham005 commented on app/src/quests_user/questsUser.service.ts
> +    return { circle: 0, value: (await firstCircle)[0].value };
await는 위에서 하고, [0]번째 없는 경우 확인합시다

2023-05-11 06:36 UTC, jpham005 commented on app/src/quests_user/questsUser.service.ts
> +    const questId: number[] = [44, 45, 46, 47, 48, 49, 37];
이거 as const 붙여주세요.
정의하는 부분이 다른 곳으로 모여있으면 더 좋긴 하겠습니다만, 딱히 좋은 아이디어가 없군요

2023-05-11 06:36 UTC, jpham005 commented on app/src/score/score.service.ts
> +      throw HttpException;
404 exception

2023-05-11 06:36 UTC, jpham005 commented on app/src/total/models/total.model.ts
> +  ValuePerCircleByPromo: ValuePerCircleByPromo[];
나중에 필요해지면 쓰죵

2023-05-11 06:36 UTC, jpham005 commented on app/src/total/total.resolver.ts
> +  //}
삭제

2023-05-11 06:36 UTC, jpham005 commented on app/src/total/total.resolver.ts
> +  }
주석

2023-05-12 08:14 UTC, jpham005 commented on app/src/personalGeneral/personal.general.resolver.ts
> +  async getPersonGeneralPage(@Args('uid') uid: number, @Context() context: Context) {
{ userProfile: UserProfile } 리턴

2023-05-12 08:14 UTC, jpham005 commented on app/src/personalGeneral/personal.general.resolver.ts
> +      // levelRank: await this.personalGeneralService.getLevelRank(uid),
주석으로 남기려면 컨벤션으로 정하고 다른 페이지에서도 똑같이 처리해야할 것 같네요

2023-05-12 08:14 UTC, jpham005 commented on app/src/personalGeneral/personal.general.resolver.ts
> +  }
리턴타입 씁시당

2023-05-12 08:14 UTC, jpham005 commented on app/src/score/score.service.ts
>      if (value === undefined) {
if (!value)

2023-05-12 13:00 UTC, jpham005 reviewed
거의 다 왔습니다

2023-05-13 05:23 UTC, jpham005 commented on app/src/personalGeneral/personal.general.service.ts
> +    );
coalitions user 로 옮겨야할 것 같습니다

2023-05-18 12:33 UTC, jpham005 commented on app/src/common/db/common.db.aggregation.ts
> +export type ValuePerDate = { date: string } & AggrNumeric;
이거 aggregation 에 사용하는 타입이면 Aggr 접두를 붙이면 좋을 것 같네요.

2023-05-18 12:33 UTC, jpham005 commented on app/src/cursus_user/cursusUser.service.ts
> +    );
```ts
const aggregate = this.aggregate<T>();

const result = await aggregate
  .append({
     $bucket: {
     blabla
     }
  })
  .addFields: {
  
  }
```
이런 느낌으로 하죠

2023-05-18 12:33 UTC, jpham005 commented on app/src/cursus_user/cursusUser.service.ts
> +    return count.length ? count : [];
ㅋㅋ

2023-05-18 12:33 UTC, jpham005 commented on app/src/home/home.resolver.ts
> +    return await this.homeService.blackholedCountByDate(start, end);
이거 service로 옮깁시다

2023-05-18 12:33 UTC, jpham005 commented on app/src/total/total.resolver.ts
> +    return await this.totalService.activeUserCountRecords(start, end);
서비스로..

2023-05-18 12:33 UTC, jpham005 commented on app/src/cursus_user/cursusUser.service.ts
> +    key: string,
cursus user의 property 만 받도록 타입 만드는게 낫겠네요.
```ts
type CursusUserDatable = 'beginAt' | 'endAt';
```

2023-05-18 12:33 UTC, jpham005 commented on app/src/total/total.service.ts
> +    );
언젠가... facet...

2023-05-18 12:33 UTC, jpham005 commented on app/src/total/total.service.ts
> +    }
이거 블랙홀 달마다 없을 경우 생각해서 고쳐야겠네요.

2023-05-18 12:33 UTC, jpham005 commented on app/src/util/time.ts
> +    const result: Object[] = [];
object~

2023-05-18 12:33 UTC, jpham005 commented on app/src/util/time.ts
> +    }
```ts
for (let currDate = new Date(start); ; currDate = moveMonth(currDate, 1)) {
  result.push(currDate);
}
```

2023-05-18 12:33 UTC, jpham005 commented on app/src/util/time.ts
> +    const result: Object[] = [];
```ts
const result: {[key: '$dateToString']: { date: string; format: string; }}
```

2023-05-18 15:45 UTC, jpham005 requested changes
time.ts 마저 수정하시고.... 몇가지 코멘트 더 달았습니다.

2023-05-18 15:45 UTC, jpham005 commented on app/src/coalitions_user/coalitionsUser.service.ts
> +    const coalition = await aggregate.match({ userId: uid });
이거 match 만 하는거면 그냥 find query 로 해결하죠?
굳이 aggregate 안해도 될 듯 합니다.

2023-05-18 15:45 UTC, jpham005 commented on app/src/cursus_user/cursusUser.service.ts
> +    return levelRank.length ? levelRank[0].value : -1;
이거 -1 반환 어떤 의미인가요?

2023-05-18 15:46 UTC, jpham005 commented
그리고 코멘트 단 부분들 해결됐으면 resolve conversation 부탁드립니다.

2023-05-19 04:10 UTC, niamu01 commented on app/src/score/score.service.ts
>      if (value === undefined) {
value가 0일 수 있어서 다시 `if (value === undefined)`로 돌아왔습니다

2023-05-19 05:43 UTC, niamu01 commented on app/src/coalitions_user/coalitionsUser.service.ts
> +    }
exception으로 통일 👍

2023-05-19 09:18 UTC, jpham005 commented on app/src/util/time.ts
> +    result.unshift(new Date('1970-01-01'));
이거 그냥 const result = [new Date('1970-01-01')];
이런 방식으로 선언하고 만들면 안되나요?

2023-05-20 02:16 UTC, jpham005 approved these changes
사실 time.ts 의 새 함수들의 이름이 좀 마음에 안들긴 합니다만...
좀 더 생각을 해봐야겠네요.
고생 많으셨습니다

2023-05-20 07:18 UTC, merged